"""Add new show fields and ticket categories

Revision ID: 0de9d5170236
Revises: 001_initial
Create Date: 2026-02-27 17:20:39.341007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de9d5170236'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types manually first for PostgreSQL
    op.execute("CREATE TYPE ticketcategory AS ENUM ('VIP', 'Premium', 'General')")
    op.execute("CREATE TYPE showtype AS ENUM ('CONCERT', 'MAGIC_SHOW', 'DANCE_SHOW')")

    op.add_column('bookings', sa.Column('ticket_category', sa.Enum('VIP', 'Premium', 'General', name='ticketcategory'), server_default='General', nullable=False))
    
    op.add_column('shows', sa.Column('show_type', sa.Enum('CONCERT', 'MAGIC_SHOW', 'DANCE_SHOW', name='showtype'), server_default='CONCERT', nullable=False))
    op.add_column('shows', sa.Column('performer_name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('shows', sa.Column('venue_name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('shows', sa.Column('city', sa.String(length=100), server_default='', nullable=False))
    op.add_column('shows', sa.Column('duration', sa.Integer(), server_default='120', nullable=False))
    op.add_column('shows', sa.Column('poster_image_url', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('vip_price', sa.Float(), server_default='0', nullable=False))
    op.add_column('shows', sa.Column('vip_total_seats', sa.Integer(), server_default='0', nullable=False))
    op.add_column('shows', sa.Column('premium_price', sa.Float(), server_default='0', nullable=False))
    op.add_column('shows', sa.Column('premium_total_seats', sa.Integer(), server_default='0', nullable=False))
    op.add_column('shows', sa.Column('general_price', sa.Float(), server_default='0', nullable=False))
    op.add_column('shows', sa.Column('general_total_seats', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('shows', 'general_total_seats')
    op.drop_column('shows', 'general_price')
    op.drop_column('shows', 'premium_total_seats')
    op.drop_column('shows', 'premium_price')
    op.drop_column('shows', 'vip_total_seats')
    op.drop_column('shows', 'vip_price')
    op.drop_column('shows', 'poster_image_url')
    op.drop_column('shows', 'duration')
    op.drop_column('shows', 'city')
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'performer_name')
    op.drop_column('shows', 'show_type')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('bookings', 'ticket_category')
    # ### end Alembic commands ###
