"""update models

Revision ID: 851ea483d93d
Revises: 0de9d5170236
Create Date: 2026-02-28 05:35:37.059828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '851ea483d93d'
down_revision: Union[str, None] = '0de9d5170236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = postgresql.ENUM('mocked', 'completed', name='paymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('bookings', sa.Column('payment_status', sa.Enum('mocked', 'completed', name='paymentstatus'), nullable=False, server_default='mocked'))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('bookings', 'ticket_category')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    show_category_enum = postgresql.ENUM('concert', 'comedy', 'theatre', 'festival', name='showcategory')
    show_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('shows', sa.Column('category', sa.Enum('concert', 'comedy', 'theatre', 'festival', name='showcategory'), nullable=False, server_default='concert'))
    op.add_column('shows', sa.Column('location', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('shows', sa.Column('rows_count', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('shows', sa.Column('seats_per_row', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('shows', sa.Column('ticket_price', sa.Float(), nullable=False, server_default='50.0'))
    op.drop_column('shows', 'poster_image_url')
    op.drop_column('shows', 'vip_total_seats')
    op.drop_column('shows', 'premium_price')
    op.drop_column('shows', 'premium_total_seats')
    op.drop_column('shows', 'general_total_seats')
    op.drop_column('shows', 'performer_name')
    op.drop_column('shows', 'city')
    op.drop_column('shows', 'duration')
    op.drop_column('shows', 'general_price')
    op.drop_column('shows', 'vip_price')
    op.drop_column('shows', 'show_type')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'role')
    op.add_column('shows', sa.Column('show_type', postgresql.ENUM('CONCERT', 'MAGIC_SHOW', 'DANCE_SHOW', name='showtype'), server_default=sa.text("'CONCERT'::showtype"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('vip_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('general_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('duration', sa.INTEGER(), server_default=sa.text('120'), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('city', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('performer_name', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('general_total_seats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('premium_total_seats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('premium_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('vip_total_seats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('poster_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('shows', 'ticket_price')
    op.drop_column('shows', 'seats_per_row')
    op.drop_column('shows', 'rows_count')
    op.drop_column('shows', 'location')
    op.drop_column('shows', 'category')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('bookings', sa.Column('ticket_category', postgresql.ENUM('VIP', 'Premium', 'General', name='ticketcategory'), server_default=sa.text("'General'::ticketcategory"), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'payment_status')
    # ### end Alembic commands ###
