"""Add flight features to booking

Revision ID: a35027a5b5f1
Revises: 851ea483d93d
Create Date: 2026-03-01 11:34:59.657684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35027a5b5f1'
down_revision: Union[str, None] = '851ea483d93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ticket_code', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('attendee_name', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('attendee_email', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('attendee_phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_bookings_ticket_code'), 'bookings', ['ticket_code'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_bookings_ticket_code'), table_name='bookings')
    op.drop_column('bookings', 'attendee_phone')
    op.drop_column('bookings', 'attendee_email')
    op.drop_column('bookings', 'attendee_name')
    op.drop_column('bookings', 'amount_paid')
    op.drop_column('bookings', 'ticket_code')
    # ### end Alembic commands ###
